name: Sync diary data from private repo

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに同期

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT_TOKEN }}
          path: private

      - name: Create data directory and copy files
        run: |
          mkdir -p data/weeks
          if [ -d "private/data/weeks" ]; then
            cp -r private/data/weeks/* data/weeks/ 2>/dev/null || echo "No data files to copy"
          fi

      - name: Commit and push synced data
        run: |
          git config user.name "Diary Sync Bot"
          git config user.email "sync-bot@example.com"
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to sync"
          else
            git commit -m "Sync diary data from private repo - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
